#!/usr/local/bin/perl -w
use strict;
use Tk;
use Tk::TFrame;
use Tk::Pane;


my $mw = Tk::MainWindow->new;

my $pane = $mw->Scrolled('Pane',
	-scrollbars => 'oe',
	-sticky => 'we',
    );


my $f = $pane->TFrame(-label => [-text => 'Toolbars'], -borderwidth => 2, -relief => 'groove');


$f->gridRowconfigure(0,-weight => 1.0);
$f->gridRowconfigure(1,-weight => 1.0);
$f->gridColumnconfigure(0,-weight => 1.0);
$f->gridColumnconfigure(1,-weight => 1.0);
$f->gridColumnconfigure(2,-weight => 1.0);
$f->gridColumnconfigure(3,-weight => 1.0);

{
 $f->Label(-text => 'Show Toolbars As:')->grid(-row => 0, -column => 0, -sticky => 'e');
 my $rv = 0;
 my @rv = (qw(Pictures Text),"Pictures and Text");
 my $i;
 for($i = 0 ; $i < @rv ; $i++) {
  $f->Radiobutton(-text => $rv[$i], -value => $i, -variable => \$rv)->grid(-row => 0, -column => $i+1, -sticky => 'w');
 }
}
my $x = $f->Label(-text => 'Toolbar Tips Are:');
$x->grid(-row => 1, -column => 0, -sticky => 'e');

$f->Checkbutton(-text => 'Enabled')->grid(-row => 1, -column => 1, -sticky => 'w');
$f->pack(-side => 'top', -fill => 'x', -padx => 5, -pady => 5);

$f = $pane->TFrame(-label => [-text => 'Startup'], -borderwidth => 2, -relief => 'groove');

$f->gridRowconfigure(0,-weight => 1.0);
$f->gridRowconfigure(1,-weight => 1.0);
$f->gridColumnconfigure(0,-weight => 1.0);
$f->gridColumnconfigure(1,-weight => 1.0);
$f->gridColumnconfigure(2,-weight => 1.0);
$f->gridColumnconfigure(3,-weight => 1.0);

{
 $f->Label(-text => 'On Startup Launch:')->grid(-row => 0, -column => 0, -sticky => 'e');
 my $rv = 0;
 my @rv = ("Browser","Mail","News");
 my $i;
 for($i = 0 ; $i < @rv ; $i++) {
  $f->Radiobutton(-text => $rv[$i], -value => $i, -variable => \$rv)->grid(-row => 0, -column => $i+1, -sticky => 'w');
 }
}

{
 $f->Label(-text => 'Browser Starts with:')->grid(-row => 1, -column => 0, -sticky => 'e');
 my $rv = 0;
 $f->Radiobutton(-text => "Blank Page", -value => 0, -variable => \$rv)->grid(-row => 1, -column => 1, -sticky => 'w');
 $f->Radiobutton(-text => "Home Page Location", -value => 1, -variable => \$rv)->grid(-row => 2, -column => 1, -sticky => 'w');
 $f->Entry()->grid(-row => 2, -column => 2, -columnspan => 2, -sticky => 'we',-ipady => 1, -ipadx => 1);
}

$f->pack(-side => 'top', -fill => 'x', -padx => 5, -pady => 5);

$pane->pack(-side => 'top', -fill => 'both',-expand => 1);

Tk::MainLoop;
__END__
