#!/usr/local/bin/perl -w

use Tk;
use Tk::NumEntryPlain;
use strict;

my $mw = new MainWindow;

my $nume = $mw->NumEntryPlain(-command => sub { print "Value = ",@_,"\n" });

$nume->pack(-side => 'top', -fill => 'x');

$nume = $mw->NumEntryPlain(
		-minvalue => 10,
		-maxvalue => 100,
		-defaultvalue => -2,
		-command => sub { print "Value = ",@_,"\n" }
);

$nume->pack(-side => 'top', -fill => 'x');

MainLoop;
